from django.urls import path,include
from rest_framework.routers import DefaultRouter
# DefaultRouter(A DRF router that automatically creates URLs for API endpoints)
from .views import DoctorViewSet, PatientViewSet, AppoinmentViewSet
# The views that handle API requests.

router = DefaultRouter() 
router.register(r'doctors', DoctorViewSet)
router.register(r'patients', PatientViewSet)
router.register(r'appoinments', AppoinmentViewSet)

urlpatterns = [
    path('', include(router.urls))
]

# .register(r'doctors', DoctorViewSet) →
# Maps DoctorViewSet to the endpoint /api/doctors/.

# include(router.urls) → Includes all API routes generated by DefaultRouter.
# The API endpoints will be automatically created, so you don’t need to manually define each route.