from django.urls import path,include
from rest_framework.routers import DefaultRouter
# DefaultRouter(A DRF router that automatically creates URLs for API endpoints)
from .views import DoctorViewSet, PatientViewSet, AppoinmentViewSet,latest_appoinment_api,home,UserRegisterView
from .views import TokenObtainPairView
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

router = DefaultRouter() 
router.register(r'doctors', DoctorViewSet)
router.register(r'patients', PatientViewSet)
router.register(r'appoinments', AppoinmentViewSet)

urlpatterns = [
    path('latest-appoinment/', latest_appoinment_api),
    path('', home, name='home'),  # This makes '/' show the homepage
    path('api/', include(router.urls)),
    path('api/register/', UserRegisterView.as_view(), name='register'),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),  # Login endpoint
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),  # Refresh token
]


# .register(r'doctors', DoctorViewSet) →
# Maps DoctorViewSet to the endpoint /api/doctors/.

# include(router.urls) → Includes all API routes generated by DefaultRouter.
# The API endpoints will be automatically created, so you don’t need to manually define each route.

