# Generated by Django 5.1.6 on 2025-02-20 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appoinment',
            old_name='Doctor',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='Name',
            new_name='name',
        ),
    ]
